from rest_framework.permissions import BasePermission

from apps.organizations.models import Membership
from utils.organization import get_organization_id

METHOD_PREFIX = {
    "GET": "view",
    "HEAD": "view",
    "POST": "add",
    "PUT": "change",
    "PATCH": "change",
    "DELETE": "delete",
}


class HasOrgPermission(BasePermission):
    """
    Organization-aware permission.

    Permission resolution happens in this order:

    1. permission_map
       Example:
           {
               "POST": "organizations.add_membership",
           }

    2. required_permission
       Example:
           "organizations.add_membership"

    3. Automatic model mapping
       Example:

           GET Membership
               -> organizations.view_membership
               -> organizations.view_own_membership

           POST Membership
               -> organizations.add_membership

           PATCH Membership
               -> organizations.change_membership

           DELETE Membership
               -> organizations.delete_membership

    For automatically generated model permissions, an own-scoped
    permission is generated using:

        <prefix>_own_<model>

    Example:

        view_membership
        view_own_membership

    The own permission is only considered when it comes from the
    automatic model mapping.

    On successful authorization this permission sets:

        request.organization_id
        request.org_membership
        request.org_scope

    org_scope is either:

        "all"
        "own"
    """

    def _required(self, request, view):
        """
        Return:

            (all_permission, own_permission)

        own_permission is only generated by the automatic model mapping.
        Explicit permission_map and required_permission values only
        specify one permission.
        """
        method = request.method

        # 1. Per-method explicit permission.
        permission_map = getattr(view, "permission_map", None) or {}

        if method in permission_map:
            return permission_map[method], None

        # 2. One explicit permission for the whole view.
        if explicit := getattr(view, "required_permission", None):
            return explicit, None

        # 3. Automatic model-based permissions.
        model = getattr(view, "model", None)
        prefix = METHOD_PREFIX.get(method)

        if model and prefix:
            meta = model._meta

            all_permission = f"{meta.app_label}.{prefix}_{meta.model_name}"

            own_permission = f"{meta.app_label}.{prefix}_own_{meta.model_name}"

            return all_permission, own_permission

        return None, None

    def has_permission(self, request, view):
        """
        Check whether the authenticated user has permission in the
        organization selected by X-Organization-ID.

        Successful checks also establish request.org_scope so that
        OrgAPIView can apply the correct queryset restriction.
        """

        # Browsers/preflight requests should not require organization
        # permission.
        if request.method == "OPTIONS":
            return True

        all_perm, own_perm = self._required(request, view)

        # A permission must be in the form:
        #
        #     app_label.codename
        #
        if not isinstance(all_perm, str) or all_perm.count(".") != 1:
            return False

        app_label, codename = all_perm.split(".", 1)

        if not app_label or not codename:
            return False

        # Resolve the organization selected by the request.
        organization_id = get_organization_id(request)

        # Find this user's membership in that organization.
        membership = (
            Membership.objects.select_related("role")
            .filter(
                user=request.user,
                organization_id=organization_id,
            )
            .first()
        )

        if membership is None:
            return False

        # Store organization context for the rest of the request.
        request.organization_id = organization_id
        request.org_membership = membership

        # Owner has unrestricted organization access.
        #
        # Therefore:
        #   - all rows
        #   - all permissions
        #   - no role permission lookup required
        if membership.is_owner:
            request.org_scope = "all"
            return True

        role = membership.role

        # A non-owner must have a role.
        if role is None:
            return False

        # Never trust a role belonging to another organization.
        if role.organization_id != organization_id:
            return False

        # Fetch all permissions assigned to the role once.
        #
        # Result is a set of:
        #
        #     (app_label, codename)
        #
        held_permissions = set(
            role.permissions.values_list(
                "content_type__app_label",
                "codename",
            )
        )

        # Organization-wide permission.
        if (app_label, codename) in held_permissions:
            request.org_scope = "all"
            return True

        # Own-only permission.
        #
        # This is primarily used for automatically generated permissions
        # such as:
        #
        #     view_own_membership
        #
        if own_perm:
            own_app_label, own_codename = own_perm.split(".", 1)

            if (own_app_label, own_codename) in held_permissions:
                request.org_scope = "own"
                return True

        return False
