# Generated by Django 6.1.1 on 2026-10-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'permissions': [('view_own_membership', 'Can view own membership')]},
        ),
    ]
