# Generated by Django 6.1.1 on 2026-10-10 09:36

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_membershipinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='membershipinvitation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('organization'), condition=models.Q(('status', 'pending')), name='uniq_pend_inv_org_email'),
        ),
    ]
